baseURL = "https://demo.gethugothemes.com/liva/examplesite/"
disqusShortname = ""
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "liva-hugo"
title = "Liva | Personal blog template"
[[menu.footer]]
name = "test"
url = "https://abhaypro.in"
weight = 4
[[menu.footer]]
URL = "contact/"
name = "Contact"
weight = 3
[[menu.footer]]
URL = "blog/"
name = "Post"
weight = 2
[[menu.footer]]
URL = "about/"
name = "About"
weight = 1
[[menu.main]]
URL = "contact/"
name = "Contact"
weight = 3
[[menu.main]]
URL = "blog/"
name = "Post"
weight = 2
[[menu.main]]
URL = "about/"
name = "About"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Shreya Blog"
copyright = "| copyright &copy; 2023 [Shreya-blog] All Rights Reserved |"
description = "This is meta description"
email = "xyz@email.com"
googleAnalitycsID = "Your ID"
home = "Home"
location = "Punjab, India"
logo = "images/logo.png"
mobile = "0124857985320"
[params.cookies]
enable = true
expire_days = 2
[params.newsletter]
content = "Nor is there anyone who loves pain itself because it is pain."
enable = true
title = "Join Our Newsletter"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
