######################## default configuration ####################
baseURL = "https://shreya-blog.netlify.app/"
languageCode = "en-us"
title = "Shreya | Personal blog "
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Post"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Shreya's Thoughts"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0124857985320"
email = "shrey2021max@gmail.com"
location = "Punjab, India"
# copyright
copyright = "| copyright &copy; 2021 [Shreya-blog] All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = "The two most important days of your life are the day that you’re born and the day that you find out why. -Mark Twain"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "Telegram"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://t.me/s_hrey_7"

[[params.social]]
title = "pintrest"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://pin.it/3UBOfgUl"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/thewriting_wizard07/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"
